version: 0.2

env:
  variables:
    NODE_ENV: production

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - node -v
      - npm -v
      - npm ci

  pre_build:
    commands:
      # Run quality checks if scripts exist; skip gracefully if not
      - npm run lint --if-present
      - npm run format:check --if-present
      - npm test --if-present

  build:
    commands:
      # For pure Express apps there may be no build step; keep it for compatibility
      - echo "Build phase completed (no compile step for plain Express)."

artifacts:
  files:
    - '**/*'
  discard-paths: no
