version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - node -v
      - npm -v
      - npm ci
  build:
    commands:
      # Optional: quick sanity check that the app file exists
      - test -f server.js || test -f app.js

artifacts:
  files:
    - '**/*'
  discard-paths: no
